// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yirpcfmcpmlcotzpvaxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpcnBjZm1jcG1sY290enB2YXhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MTA2ODQsImV4cCI6MjA2OTA4NjY4NH0.K5_FOEfXnGFK-8SBBXa_r4yV5dn1Dd9u0NvH91iN9yQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});